Fix contact section
Leboroz/Portfolio-setup-and-mobile-version-skeleton pull request #3
Opened 2021-09-21 22:32 UTC by Leboroz

I changed the div for a form tag and wrapped every field with a li tag

2021-09-21 23:06 UTC, safafa requested changes
## STATUS: CHANGES REQUESTED ♻️ 

Hi @Leboroz  @alvinlouis29 , You did a great job so far 👏🏼 👏🏼 

- Well done on following the original design.

However, here are some points that you need to work on to get your project approved.

## Required changes :

- [ ] Check the inline comments.

## Optional changes :
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-21 23:06 UTC, safafa commented on views/index.html
> +        </form>
- [ ] The form must have a submit button. You can use a button with the type submit or an input type submit. I suggest moving the ` Start collaboration` button inside the form and adding `type="submit"` attribute to it.

2021-09-21 23:06 UTC, safafa commented on views/index.html
> +          <ul>
![image](https://user-images.githubusercontent.com/43698511/134258636-5bbacc11-6719-4585-8b21-0f502fb2098f.png)

- [ ] As requested in the project requirements You must collect data using Formspree. Kindly make the change to made the form functional.

2021-09-21 23:24 UTC, Leboroz commented on views/index.html
> +          <ul>
Thank you for your feedback! 🤟

2021-09-22 17:30 UTC, SajjadAhmad14 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi Leo Albornoz Cubillán, 
## Congratulations 🎉 Thank you for implementing changes suggested previously 🙏

## Happy Coding 👏👏👏
#### Please leave any questions or comments in the PR if you have any doubts or unclarity!
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-09-22 17:33 UTC, merged